<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class QuestionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('questions')->truncate();

        DB::table('questions')->insert([
            ['id' => 1, 'quiz_id' => 2, 'title' => 'Który film z 1985 roku zawiera cytat "88 mil na godzię!"?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 2, 'quiz_id' => 2,'title' => 'Który film z 1959 roku zdobył 11 Oscarów?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 3, 'quiz_id' => 2,'title' => 'W którym filmie o Jamesie Bondzie miała miejsce następująca wymiana zdań: "Spodziewasz się, że będę mówił?" "Nie, panie Bond, oczekuję, że pan umrze!"?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 4, 'quiz_id' => 2,'title' => 'Kto zdobył Oscary 2012 dla Aktora w roli głównej?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 5, 'quiz_id' => 2,'title' => 'Który flim zdobył Oscary 2012 w kategorii Najlepszy pełnometrażowy film animowany?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 6, 'quiz_id' => 2,'title' => 'Jaki jest jedyny film Disneya, który został nominowany do 13 nagrody Oscara?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            ['id' => 7, 'quiz_id' => 3,'title' => 'Pierwszy powojenny polski film to:',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 8, 'quiz_id' => 3,'title' => 'Reżyserem filmu "Kanał" jest:',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 9, 'quiz_id' => 3,'title' => 'Pierwszy powojenny polski kolorowy film to:',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 10, 'quiz_id' => 3,'title' => 'Polski film, który obejrzała największa liczba widzów przed rokiem 1989, to:',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 11, 'quiz_id' => 3,'title' => 'Jak nazywa się reżyser, który otrzymał Oscara za całokrztałt twórczości?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 12, 'quiz_id' => 3,'title' => 'Najdroższy polski film po 1989 roku to:',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 13, 'quiz_id' => 3,'title' => 'Zdzisław Maklakiewicz i Jan Himilsbach grają wspólnie w filmie:',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 14, 'quiz_id' => 3,'title' => 'Kto jest reżysetem filmu "Nóż w wodzie"?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 15, 'quiz_id' => 3,'title' => 'Zbigniew Cybulski - jego największe osiągnięcie to rola w filmie:',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 16, 'quiz_id' => 3,'title' => 'Główną rolę kobiecą w filmie "Lalka" zagrała:',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 17, 'quiz_id' => 3,'title' => 'Aktor, który zagrał we wszystkich częściach Trylogii, to:',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            ['id' => 18, 'quiz_id' => 1,'title' => 'Jakie wydarzenie miało miejsce w 966r. ?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 19, 'quiz_id' => 1,'title' => 'Pierwsza stolica Polski to:','created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 20, 'quiz_id' => 1,'title' => 'Kiedy wybuchła I wojna światowa?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 21, 'quiz_id' => 1,'title' => 'Który z poniższych królów był królem elekcyjnym? ', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 22, 'quiz_id' => 1,'title' => 'Czego dotyczyła Unia Lubelska?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 23, 'quiz_id' => 1,'title' => 'Jaka bitwa stoczyła się 15 Lipca w 1410r.?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 24, 'quiz_id' => 1,'title' => 'Kim byli Jagiellonowie?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 25, 'quiz_id' => 1,'title' => 'Ile lat Polska była pod zaborami ?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 26, 'quiz_id' => 1,'title' => '22 stycznia 1863 roku wybuchło powstanie styczniowe. Przeciw jakiemu imperium Polska stawiła czoło?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 27, 'quiz_id' => 1,'title' => 'Który król miał przydomek  "mocny"  ?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            ['id' => 28, 'quiz_id' => 4,'title' => 'Kiedy urodził się Mata?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 29, 'quiz_id' => 4,'title' => 'Kiedy jego ojciec wymyślił mu pseudonim?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 30, 'quiz_id' => 4,'title' => 'Ile sióstr ma Michał?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 31, 'quiz_id' => 4,'title' => 'Kiedy Mata przebił barierę 2 milionów słuchaczy na Spotify?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 32, 'quiz_id' => 4,'title' => 'Którego dnia października został wydany album Maty "Młody Matczak"?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 33, 'quiz_id' => 4,'title' => 'Jakie jest panieńskie nazwisko jego mamy?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 34, 'quiz_id' => 4,'title' => 'Jaki napój znajdował się w jego zestawie w McDonalds?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 35, 'quiz_id' => 4,'title' => 'Kto był patronem jego liceum?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 36, 'quiz_id' => 4,'title' => 'Do kogo Michał odwoływał się w swoim eseju?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 37, 'quiz_id' => 4,'title' => 'Kiedy wydał pierwszy kawałek pod pseudonimem "Skute Bobo"?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 38, 'quiz_id' => 4,'title' => 'Współzałożycielem jakiej fundacji jest Mata?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            ['id' => 39, 'quiz_id' => 5,'title' => 'Jak miał na imię ojciec Mei?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 40, 'quiz_id' => 5,'title' => 'Kto był ulubieńcem Priyi z 4*Town?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 41, 'quiz_id' => 5,'title' => 'W jaki dzień przypadały urodziny Taylora?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 42, 'quiz_id' => 5,'title' => 'Kto był przodkiem Mei?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 43, 'quiz_id' => 5,'title' => 'Jak miał na imię chłopak, który pracował w sklepie?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 44, 'quiz_id' => 5,'title' => 'Jaką piosenkę wykonywali 4*Town?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 45, 'quiz_id' => 5,'title' => 'Ile przyjaciółek miała Mei?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 46, 'quiz_id' => 5,'title' => 'Jak miał na imię szkolny ochroniarz?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 47, 'quiz_id' => 5,'title' => 'Ile członków miał zespół 4*Town?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 48, 'quiz_id' => 5,'title' => 'Co zmieniło się w Mei po przemianie w czerwoną pandę?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            ['id' => 49, 'quiz_id' => 6,'title' => 'Kto w 1840 roku spopularyzował trend na białą suknię dla panny młodej?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 50, 'quiz_id' => 6,'title' => 'Prawda czy fałsz: w starożytnym Rzymie goście łamali chleb nad głową panny młodej, aby zwiększyć płodność?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 51, 'quiz_id' => 6,'title' => 'Skąd pochodzi określenie "miesiąc miodowy"?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 52, 'quiz_id' => 6,'title' => 'Jaki przedmiot miał przynieść szczęście pannie młodej, noszony w dniu ślubu?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 53, 'quiz_id' => 6,'title' => 'Co dodawano do bukietu ślubnego, aby odpędzić złe duchy, w średniowieczu?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 54, 'quiz_id' => 6,'title' => 'Według angielskiego folkloru, co oznacza znalezienie pająka w sukni ślubnej?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 55, 'quiz_id' => 6,'title' => 'Co noszą panny młode, aby chronić się od złych duchów?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 56, 'quiz_id' => 6,'title' => 'Gdzie rozpoczęto tradycję wymiany pierścieni, jako symbol oddania i wierności?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 57, 'quiz_id' => 6,'title' => 'Według angielskiej tradycji, który dzień tygodnia jest najpopularniejszy, aby wziąć ślub?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 58, 'quiz_id' => 6,'title' => 'Jakiego prezentu nie powinno się dawać parze ślubnej?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 59, 'quiz_id' => 6,'title' => 'Prawda czy fałsz: małżeństwa osób tej samej płci były uznawane w starożytnym Rzymie do 342 r. n.e.',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 60, 'quiz_id' => 6,'title' => 'W Czechach nie obrzuca się ryżem nowożeńców. Zamiast tego rzucają…',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 61, 'quiz_id' => 6,'title' => 'Dlaczego czerwiec jest miesiącem, w którym najczęściej odbywają się ceremonie ślubne?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 62, 'quiz_id' => 6,'title' => 'Jaki miesiąc jest zatem najbardziej pechowy do brania ślubu?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            ['id' => 63, 'quiz_id' => 7,'title' => 'W którym roku rozpadł się związek Adama Zdrójkowskiego i Wiktorii Gąsiewskiej?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 64, 'quiz_id' => 7,'title' => 'W którym roku rozpadł się związek Shawna Mendesa i Camilli Cabello?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 65, 'quiz_id' => 7,'title' => 'W którym roku rozpadł się związek Kacpra Błońskiego i Julii Kostery?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 66, 'quiz_id' => 7,'title' => 'W którym roku rozpadł się związek Pawła Tyburskiego i Moniki Kozakiewicz?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 67, 'quiz_id' => 7,'title' => 'W którym roku rozpadł się związek Matthewa Tylera Vorce i Billie Eilish?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 68, 'quiz_id' => 7,'title' => 'W którym roku rozpadł się związek Przemka Kossakowskiego i Martyny Wojciechowskiej?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 69, 'quiz_id' => 7,'title' => 'W którym roku rozpadł się związek Marcina Hakiela i Katarzyny Cichopek?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 70, 'quiz_id' => 7,'title' => 'W którym roku rozpadł się związek Marcina Dubiela i Lexy?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            ['id' => 71, 'quiz_id' => 8, 'title' => 'Dobra na początek lajtowo. Jaka jest prędkość maksymalna Ferrari LaFerrari?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 72, 'quiz_id' => 8,'title' => 'W ile przyspiesza do setki Nissan GT-R?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 73, 'quiz_id' => 8,'title' => 'W którym roku powstało Bugatti Veyron?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 74, 'quiz_id' => 8,'title' => 'Co jest szybsze?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 75, 'quiz_id' => 8,'title' => 'Co to jest za samochód?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 76, 'quiz_id' => 8,'title' => 'Który jest szybszy?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 77, 'quiz_id' => 8,'title' => 'Który samochód jest droższy?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 78, 'quiz_id' => 8,'title' => 'Która firma jest starsza?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 79, 'quiz_id' => 8,'title' => 'Która marka nie należy do Volkswagena?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 80, 'quiz_id' => 8,'title' => 'Ostatnie pytanie! Co jest następcą Ferrari F50?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            ['id' => 81, 'quiz_id' => 9,'title' => 'Kto wymyślił logo Alfa Romeo?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 82, 'quiz_id' => 9,'title' => 'Jaki samochód był pierwszym, który wszedł do produkcji seryjnej?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 83, 'quiz_id' => 9,'title' => 'W którym roku pojawiły się pierwsze obowiązkowe tablice rejestracyjne?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 84, 'quiz_id' => 9,'title' => 'Do czego nawiązuje błyskawica w logo Opla?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 85, 'quiz_id' => 9,'title' => 'W jakim kraju pojawiła się pierwsza sygnalizacja świetlna?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 86, 'quiz_id' => 9,'title' => 'Kto stworzył pierwszy parkomat?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 87, 'quiz_id' => 9,'title' => 'Od czego pochodzi skrót BMW?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 88, 'quiz_id' => 9,'title' => 'Kiedy skoda zaczęła produkować samochody?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 89, 'quiz_id' => 9,'title' => 'Kim pierwotnie chciał zostać Enzo Anselmo Ferrari, założyciel koncernu Ferrari?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 90, 'quiz_id' => 9,'title' => 'Od czego pochodzi nazwa "Mercedes"?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 91, 'quiz_id' => 9,'title' => 'Co symbolizują ramiona gwiazdy Mercedesa?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 92, 'quiz_id' => 9,'title' => 'Czym na początku zajmowała się firma Peugeot?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 93, 'quiz_id' => 9,'title' => 'Jaka marka wprowadziła pasy bezpieczeństwa?',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            ['id' => 94, 'quiz_id' => 10,'title' => 'Na początek proste pytanie. Autoportret to w internetowym slangu:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 95, 'quiz_id' => 10,'title' => 'Skrót IMHO oznacza:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 96, 'quiz_id' => 10,'title' => 'Zdjęcie lub film przedstawiający coś z perspektywy osoby nagrywającej, jest oznaczany jako:',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 97, 'quiz_id' => 10,'title' => 'Używając na Instagramie skrótu AMA zapraszamy innych do:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 98, 'quiz_id' => 10,'title' => 'Co oznacza skrót L4L?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 99, 'quiz_id' => 10,'title' => 'Storiki publikujemy:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 100, 'quiz_id' => 10,'title' => 'Kiedy chcemy stanowczo uciąć jakąś dyskusję, możemy użyć skrótu:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 101, 'quiz_id' => 10,'title' => 'Skrót DM oznacza:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 102, 'quiz_id' => 10,'title' => '"Rel" piszemy w komentarzu, kiedy:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 103, 'quiz_id' => 10,'title' => 'Skrót RT oznacza:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            ['id' => 104, 'quiz_id' => 11,'title' => 'Witaj w teleturnieju ,,Milionerzy"! Ten quiz jest przeznaczony zarówno dla prawdziwych znawców, jak i zwykłych osób, które lubią przebywać w sieci. Quiz jest dość trudny. Życzę powodzenia! Pytanie za 500 złotych: Kiedy zaprojektowano pierwszy komputer?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 105, 'quiz_id' => 11,'title' => 'Pytanie za 1000 złotych: Co oznacza skrót ,,WWW"?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 106, 'quiz_id' => 11,'title' => 'Pytanie za 2000 złotych: Kiedy w Polsce zarejestrowano krajową domenę ,,pl"?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 107, 'quiz_id' => 11,'title' => 'Pytanie za 5000 złotych: Kiedy wysłano pierwszy mail na świecie?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 108, 'quiz_id' => 11,'title' => 'Pytanie za 10000 złotych: Jaką nazwę nosi użytkownik, który opublikował pierwszy film na YouTube?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 109, 'quiz_id' => 11,'title' => 'Pytanie za 20000 złotych: Jaką nazwę nosi najdłuższy na świecie podmorski kabel telekomunikacyjny?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 110, 'quiz_id' => 11,'title' => 'Pytanie za 40000 złotych: Kiedy po raz pierwszy zainfekowano komputer wirusem?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 111, 'quiz_id' => 11,'title' => 'Pytanie za 75000 złotych: W którym roku powstał pierwszy program do tworzenia grafik?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 112, 'quiz_id' => 11,'title' => 'Pytanie za 125000 złotych: Kiedy przekroczono liczbę miliarda użytkowników na Instagramie?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 113, 'quiz_id' => 11,'title' => 'Pytanie za 250000 złotych: Od kiedy spółka Apple jest notowane na spółce NASDAQ?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 114, 'quiz_id' => 11,'title' => 'Pytanie za 500000 złotych: Nazwa ,,Internet" to skrótowiec. Co dosłownie oznacza pełna nazwa Internetu?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 115, 'quiz_id' => 11,'title' => 'Pytanie za 1000000 złotych: Jakiej jednej rzeczy z podanych nie gwarantuje konto premium na Spotify?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            ['id' => 116, 'quiz_id' => 12,'title' => 'Wracasz do domu o późnej porze, bo musiałeś zostać dłużej w pracy. Jedziesz powoli przez ciemny las. Jesteś bardzo zmęczony, dlatego Twoja zdolność do podejmowania decyzji i oceny otoczenia spada. Wszystko idzie po Twojej myśli, aż tu nagle dostrzegasz człowieka, który idąc, korzysta z telefonu. W pewnej chwili dosłownie wpada pod Twoją maskę! Młody mężczyzna upada na pobocze i upuszcza telefon. Co robisz?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 117, 'quiz_id' => 12,'title' => 'Po zabezpieczeniu miejsca wypadku wychodzisz i podbiegasz do poszkodowanego. Ten leży na wznak na ulicy i ma widoczne rany na ręce i nodze. Dodatkowo ma prawdopodobnie krwotok z ust. Nie wiadomo jednak, czy doświadczył urazów wewnętrznych. Co robisz?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 118, 'quiz_id' => 12,'title' => 'Okazuje się, że ranny nie oddycha. Jak zachowasz się, dzwoniąc po karetkę?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 119, 'quiz_id' => 12,'title' => 'Karetka została wysłana pod wskazany adres, ale czas ucieka! Jak teraz postąpisz?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 120, 'quiz_id' => 12,'title' => 'Dobrze, rozpoczynasz RKO. Ale od czego należy zacząć?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 121, 'quiz_id' => 12,'title' => 'Zauważasz, że kawałek szkła utkwił w ranie poszkodowanego. Co zamierzasz z tym zrobić?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 122, 'quiz_id' => 12,'title' => 'Dostrzegasz, że prawa noga rannego jest najprawdopodobniej złamana. Jak zamierzasz postąpić?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 123, 'quiz_id' => 12,'title' => 'Co będziesz robić do przyjazdu karetki?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            ['id' => 124, 'quiz_id' => 13,'title' => 'Co wynalazł Alfred Nobel?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 125, 'quiz_id' => 13,'title' => 'Wskaż wcześniej stosowany zegar:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 126, 'quiz_id' => 13,'title' => 'Jaki kryptonim nosił program naukowo-badawczy, w wyniku którego udało się skonstruować broń atomową?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 127, 'quiz_id' => 13,'title' => 'Johannes Gutenberg opracował jeden z bardziej przełomowych wynalazków w historii Europy i świata. Co to było?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 128, 'quiz_id' => 13,'title' => 'Pierwszy układ scalony (w pełnym tego słowa znaczeniu) został stworzony w XX w. W jakich latach miało to miejsce?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 129, 'quiz_id' => 13,'title' => 'Który z poniższych wynalazków jest dziełem Polaka?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 130, 'quiz_id' => 13,'title' => 'Najstarsze ślady użytkowania szkła pochodzą sprzed:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 131, 'quiz_id' => 13,'title' => 'W którym roku powstał pierwszy znany prototyp komputera?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 132, 'quiz_id' => 13,'title' => 'Jakiej produkcji był pierwszy sztuczny satelita wyniesiony na orbitę okołoziemską?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 133, 'quiz_id' => 13,'title' => 'Ile trwał pierwszy udany lot samolotem?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 134, 'quiz_id' => 13,'title' => 'Gdzie najprawdopodobniej zostało wynalezione koło?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 135, 'quiz_id' => 13,'title' => 'Jak brzmiały pierwsze słowa wypowiedziane przez telefon?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 136, 'quiz_id' => 13,'title' => 'Jakiej narodowości był konstruktor pierwszego telewizora oraz noktowizora?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 137, 'quiz_id' => 13,'title' => 'W którym wieku wynaleziono okulary?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 138, 'quiz_id' => 13,'title' => 'Czy prawdą jest, że samochód został wynaleziony przez Henriego Forda?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 139, 'quiz_id' => 13,'title' => 'W wyniku wynalezienia przez Jamesa Watta maszyny parowej nastąpiła rewolucja przemysłowa. W którym roku dokonał on swojego wynalazku?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 140, 'quiz_id' => 13,'title' => 'Komu zawdzięczamy wynalezienie kinematografu?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 141, 'quiz_id' => 13,'title' => 'W jakim celu został stworzony Internet?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 142, 'quiz_id' => 13,'title' => 'Kto jako pierwszy wynalazł i opatentował żarówkę?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 143, 'quiz_id' => 13,'title' => 'Której cywilizacji zawdzięczamy wynalezienie czarnego prochu?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            ['id' => 144, 'quiz_id' => 14,'title' => 'Symbolem urzędów pocztowych w wielu krajach, także i w Polsce, jest:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 145, 'quiz_id' => 14,'title' => 'Uzupełnij tytuł amerykańskiego dramatu kryminalnego na podstawie powieści Jamesa Caina - „Listonosz zawsze dzwoni ____________”', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 146, 'quiz_id' => 14,'title' => '„Medytacje wiejskiego listonosza” to piosenka z repertuaru zespołu:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 147, 'quiz_id' => 14,'title' => 'Listonosz polski to bardzo stara rasa gołębia hodowana i znana od stuleci w rejonie m.in. Bochni, Niepołomic, Tarnowa i Wieliczki, czyli na terenie:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 148, 'quiz_id' => 14,'title' => 'Listonosz Edzio pojawiał się w serialu komediowym „Świat według Kiepskich”. Który aktor wcielił się w tę rolę?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 149, 'quiz_id' => 14,'title' => 'Muzeum Poczty i Telekomunikacji, jedyne w Polsce muzeum gromadzące eksponaty dokumentujące historię poczty, telekomunikacji i telegrafii na ziemiach polskich, znajduje się w mieście znanym z Panoramy Racławickiej. O które miasto chodzi?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 150, 'quiz_id' => 14,'title' => 'W filmie „Listonosz” znany poeta Pablo Neruda, przebywający na włoskiej wyspie z powodów politycznych, zaprzyjaźnia się ze swoim prywatnym listonoszem i pomaga mu zdobyć serce dziewczyny, ucząc go sztuki pisania wierszy miłosnych. Z którego kraju pochodził noblista Pablo Neruda?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 151, 'quiz_id' => 14,'title' => '„Portret listonosza Józefa Roulina” to zbiorczy tytuł 6 obrazów namalowanych w latach 1888-1889 przez słynnego holenderskiego postimpresjonistę podczas jego pobytu w Arles. Jak brzmi nazwisko tego artysty?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 152, 'quiz_id' => 14,'title' => 'Brytyjski serial animowany dla dzieci, opowiadający przygody sympatycznego listonosza z fikcyjnego miasteczka Zielona Dolina w hrabstwie Yorkshire, nosi tytuł:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 153, 'quiz_id' => 14,'title' => 'Na podstawie powieści Davida Brina „Listonosz” powstał film „Wysłannik przyszłości”. Jak nazywa się widoczny na zdjęciu reżyser tego filmu i jednocześnie aktor grający główną rolę?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            ['id' => 154, 'quiz_id' => 15,'title' => '"Panny z Wilka" to polsko-francuski film psychologiczny z 1979 roku w reżyserii Andrzeja Wajdy, będący adaptacją opowiadania:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 155, 'quiz_id' => 15,'title' => 'Panny z Awinionu to jedno z najbardziej znanych malowideł Pabla Picassa, przedstawiające pięć prostytutek z ulicy d Avinyo w Barcelonie, nieopodal której mieszkał artysta. Obraz ma wiele cech i stanowi zapowiedź stylu:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 156, 'quiz_id' => 15,'title' => 'Panienka z okienka to fikcyjna postać mieszczanki, a zarazem element folkloru i promocji:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 157, 'quiz_id' => 15,'title' => 'Kto jest autorem powieści "Szaleństwa panny Ewy" opowiadającej o przygodach szesnastoletniej Ewy Tyszowskiej?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 158, 'quiz_id' => 15,'title' => 'Według zwyczaju panna młoda na ślubie powinna mieć coś nowego, coś starego, coś pożyczonego i coś:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 159, 'quiz_id' => 15,'title' => 'Uzupełnij tytuł powieści Tomasza Tryzny, opublikowanej w 1994, a w 1996 zekranizowanej przez Andrzeja Wajdę: "Panna ____________".', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 160, 'quiz_id' => 15,'title' => 'Jak brzmiało nazwisko pięciu sióstr, panien na wydaniu, w książce "Duma i uprzedzenie" autorstwa Jane Austen?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 161, 'quiz_id' => 15,'title' => 'Kto jest autorem obrazu "Panny dworskie" z  1656 roku, uznanego zarówno przez historyków sztuki, jak i przez artystów, za jedno z największych dzieł w historii sztuki?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 162, 'quiz_id' => 15,'title' => 'Główna bohaterka powieści Kornela Makuszyńskiego "Panna z mokrą głową", opublikowanej w 1932 roku, miała na imię:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 163, 'quiz_id' => 15,'title' => '"Stara panna" to powieść z 1836 z cyklu "Komedia ludzka", zawierająca szczegółowy opis środowiska i życia tytułowej starej panny, Róży Cormon. Kto jest autorem tej powieści i całego cyklu?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            ['id' => 164, 'quiz_id' => 16, 'title' => 'Kto stworzył HTML?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 165, 'quiz_id' => 16, 'title' => 'Jaką mamy obecnie wersję HTML?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 166, 'quiz_id' => 16, 'title' => 'Co oznacza znacznik h1 ?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 167, 'quiz_id' => 16, 'title' => 'Do czego służy HTML?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 168, 'quiz_id' => 16, 'title' => 'Jaką mamy teraz wersję CSS?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 169, 'quiz_id' => 16, 'title' => 'Do czego służy CSS?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 170, 'quiz_id' => 16, 'title' => 'Jaki jest kod na tło strony?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 171, 'quiz_id' => 16, 'title' => 'Czy w CSS można robić animacje na stronie?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 172, 'quiz_id' => 16, 'title' => 'Jaka organizacja napisała CSS?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 173, 'quiz_id' => 16, 'title' => 'Czy wszystkie przeglądarki wspólpracują z CSS?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            ['id' => 174, 'quiz_id' => 17, 'title' => 'Która z tych rang jest najniższa?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 175, 'quiz_id' => 17, 'title' => 'Na której z tych map nie możemy grać meczu turniejowego?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 176, 'quiz_id' => 17, 'title' => 'Po jakim czasie wybucha bomba podłożona przez terrorystów?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 177, 'quiz_id' => 17, 'title' => 'Jaką organizacją jest Virtus.pro?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 178, 'quiz_id' => 17, 'title' => 'Ile maksymalnie granatów możemy posiadać naraz?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 179, 'quiz_id' => 17, 'title' => 'Która ze strzelb/shotgunów zadaje największy damage?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 180, 'quiz_id' => 17, 'title' => 'Co zadaje największy damage?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 181, 'quiz_id' => 17, 'title' => 'Ile maksymalnie możemy mieć pieniędzy na zakup broni?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 182, 'quiz_id' => 17, 'title' => 'Która z tych wersji Counter-Strike jest najstarsza?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 183, 'quiz_id' => 17, 'title' => 'Która z tych broni nie jest  już dostępna w CS:GO?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 184, 'quiz_id' => 17, 'title' => 'Który z tych granatów jest najdroższy?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 185, 'quiz_id' => 17, 'title' => 'Której z tych broni nie kupimy po stronie terrorystów?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 186, 'quiz_id' => 17, 'title' => 'Która z tych broni ma najpojemniejszy magazynek?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 187, 'quiz_id' => 17, 'title' => 'Jaka jest cena AK-47?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 188, 'quiz_id' => 17, 'title' => 'Która z tych broni jest najdroższa?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 189, 'quiz_id' => 17, 'title' => 'Która z tych broni nie jest shotgunem?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 190, 'quiz_id' => 17, 'title' => 'Jaką pojemność ma magazynek FAMASA?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 191, 'quiz_id' => 17, 'title' => 'Która z tych broni przeładowuje się najdłużej?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 192, 'quiz_id' => 17, 'title' => 'Jaki jest efektywny zasięg AK-47?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 193, 'quiz_id' => 17, 'title' => 'Gdzie najprawdopodobniej rozgrywa się akcja na mapie Cache?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 194, 'quiz_id' => 17, 'title' => 'Która z tych rang jest najwyższa?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 195, 'quiz_id' => 17, 'title' => 'Który z tych skinów do AK-47 nie istnieje?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 196, 'quiz_id' => 17, 'title' => 'Która z tych map została dodana do CS:GO?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 197, 'quiz_id' => 17, 'title' => 'Ile granatów jest dostępnych w grze?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 198, 'quiz_id' => 17, 'title' => 'Ile jest czerwonych skinów do AK-47?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 199, 'quiz_id' => 17, 'title' => 'Na jakiej mapie celując w słońce sprawimy, że zniknie ?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 200, 'quiz_id' => 17, 'title' => 'Na jakiej mapie możemy usłyszeć dźwięk z gry PORTAL?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 201, 'quiz_id' => 17, 'title' => 'Na której z tych map możemy zagrać mecz turniejowy?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 202, 'quiz_id' => 17, 'title' => 'Która z tych map jest mapą niemiecką?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 203, 'quiz_id' => 17, 'title' => 'Skąd pochodzi shotgun XM1014?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            ['id' => 204, 'quiz_id' => 18, 'title' => 'Kreuzen Sie die richtige Aussage an:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 205, 'quiz_id' => 18, 'title' => 'Welches Verb passt?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 206, 'quiz_id' => 18, 'title' => 'Welche Aussage ist richtig?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 207, 'quiz_id' => 18, 'title' => 'Welcher Plural ist falsch?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 208, 'quiz_id' => 18, 'title' => 'Welche Aussage ist richtig?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 209, 'quiz_id' => 18, 'title' => 'Welche Antwort ist richtig?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 210, 'quiz_id' => 18, 'title' => 'Kreuzen Sie das richtige Satzende an? „Um 10.00 Uhr beginnt der Unterricht, ...“', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 211, 'quiz_id' => 18, 'title' => 'Welche Aussage ist richtig?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 212, 'quiz_id' => 18, 'title' => 'Welcher Satz ist richtig?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 213, 'quiz_id' => 18, 'title' => 'Welche Aussage ist richtig?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 214, 'quiz_id' => 18, 'title' => 'Welches Wort ist richtig? --> Weil der Film so langweilig war, bin ich im Kino ...', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 215, 'quiz_id' => 18, 'title' => 'Welcher Satz ist am höflichsten? Sie sind in einem Café und möchten einen Tee.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 216, 'quiz_id' => 18, 'title' => 'Wie lautet die richtige Antwort auf die Frage: Wissen Sie, wo der Bahnhof ist?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 217, 'quiz_id' => 18, 'title' => 'Welche ist die richtige Antwort zur folgenden Frage: „Hast du deinem Vater das Geschenk schon gegeben?“', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 218, 'quiz_id' => 18, 'title' => 'Welcher Satz ist richtig?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 219, 'quiz_id' => 18, 'title' => 'Welches Wort passt?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 220, 'quiz_id' => 18, 'title' => 'Welche Verbform passt?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 221, 'quiz_id' => 18, 'title' => 'Welche Antwort ist richtig? „Hast du gehört? Gabi hat sich einen Porsche gekauft. Woher glaubst du hat sie so viel Geld?“', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 222, 'quiz_id' => 18, 'title' => 'Welche Aussage hat die gleiche Bedeutung als: „Er könnte krank sein“?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 223, 'quiz_id' => 18, 'title' => 'Welcher Satz hat die gleiche Bedeutung wie "Mein Französisch muss besser werden!"', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 224, 'quiz_id' => 18, 'title' => 'Welcher Satz hat die gleiche Bedeutung Er fragt sie: "Kannst du mir sagen, wie spät es ist?"', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 225, 'quiz_id' => 18, 'title' => 'Welche Aussage ist richtig gebildet?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 226, 'quiz_id' => 18, 'title' => 'Welche Aussage ist richtig gebildet?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 227, 'quiz_id' => 18, 'title' => 'Welcher Satz ist richtig gebildet?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 228, 'quiz_id' => 18, 'title' => 'Welche Aussage ist richtig gebildet?', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            ['id' => 229, 'quiz_id' => 19, 'title' => 'Jajko na miękko gotujemy przeważnie:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 230, 'quiz_id' => 19, 'title' => 'Tradycyjne placki ziemniaczane przygotowujemy z ziemniaków:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 231, 'quiz_id' => 19, 'title' => 'eklowanie to:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 232, 'quiz_id' => 19, 'title' => 'Do przygotowania tradycyjnych kiszonych ogórków potrzebujemy między innymi:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 233, 'quiz_id' => 19, 'title' => 'Podstawowym składnikiem włoskiego dania zwanego risotto jest:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            ['id' => 234, 'quiz_id' => 20, 'title' => 'Wywodząca się z kuchni kresowej kutia to słodki deser, którego głównymi składnikami są:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 235, 'quiz_id' => 20, 'title' => 'Pampuchy to tradycyjnie jadane na Kujawach:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 236, 'quiz_id' => 20, 'title' => 'Chałka to słodkie, drożdżowe pieczywo wywodzące się z kuchni:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 237, 'quiz_id' => 20, 'title' => 'To miasto słynie z obwarzanków, uznawanych oficjalnie za produkt kuchni regionalnej. Chodzi o:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 238, 'quiz_id' => 20, 'title' => 'Do przygotowania tradycyjnej zupy zwanej zalewajką potrzebujemy przede wszystkim ziemniaków oraz:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 239, 'quiz_id' => 20, 'title' => 'Napój z serwatki z mleka owczego, popularny na Podhalu, to:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 240, 'quiz_id' => 20, 'title' => 'Pod nazwą kindziuk kryje się popularna na Podlasiu, a wywodząca się z kuchni litewskiej:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 241, 'quiz_id' => 20, 'title' => 'Tradycyjnym na Śląsku dodatkiem do rolady i klusek jest:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 242, 'quiz_id' => 20, 'title' => 'Popularne na Suwalszczyźnie i Mazurach kartacze to:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 243, 'quiz_id' => 20, 'title' => 'Kwaśnica to sycąca zupa na bazie mięsa i kiszonej kapusty, chętnie jadana:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 244, 'quiz_id' => 20, 'title' => 'Wielkopolska potrawa znana jako "pyry z gzikiem" to:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 245, 'quiz_id' => 20, 'title' => 'Bułka drożdżowa z cebulą i makiem to znak rozpoznawczy kuchni z rejonu:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 246, 'quiz_id' => 20, 'title' => 'Główny składnik smorodinówki, czyli nalewki wywodzącej się z tradycji kulinarnej Kresów, to:', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            ['id' => 247, 'quiz_id' => 21, 'title' => 'Siedem', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 248, 'quiz_id' => 21, 'title' => 'Siedem', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 249, 'quiz_id' => 21, 'title' => 'Siedem', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 250, 'quiz_id' => 21, 'title' => 'Siedem', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 251, 'quiz_id' => 21, 'title' => 'Siedem', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 252, 'quiz_id' => 21, 'title' => 'Siedmiu', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 253, 'quiz_id' => 21, 'title' => 'Siódmej', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            ['id' => 254, 'quiz_id' => 22, 'title' => '__________ Szpakowski', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 255, 'quiz_id' => 22, 'title' => '__________ Borek', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 256, 'quiz_id' => 22, 'title' => '__________ Babiarz', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 257, 'quiz_id' => 22, 'title' => '__________ Zimoch', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 258, 'quiz_id' => 22, 'title' => '__________ Szaranowicz', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 259, 'quiz_id' => 22, 'title' => '__________ Swędrowski', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 260, 'quiz_id' => 22, 'title' => '__________ Laskowski', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 261, 'quiz_id' => 22, 'title' => '__________ Jaroński', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 262, 'quiz_id' => 22, 'title' => '__________ Pindera', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 263, 'quiz_id' => 22, 'title' => '__________ Dębowski', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            ['id' => 264, 'quiz_id' => 23, 'title' => 'Wiśnia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 265, 'quiz_id' => 23, 'title' => 'Kawa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 266, 'quiz_id' => 23, 'title' => 'Apartheid', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 267, 'quiz_id' => 23, 'title' => 'Fiord', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 268, 'quiz_id' => 23, 'title' => 'But', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 269, 'quiz_id' => 23, 'title' => 'Szampan', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 270, 'quiz_id' => 23, 'title' => 'Bank', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 271, 'quiz_id' => 23, 'title' => 'Napalm', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 272, 'quiz_id' => 23, 'title' => 'Wampir', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 273, 'quiz_id' => 23, 'title' => 'Puszta', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        ]);
    }
}
